# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_AI_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import socket
import sys
import cv2
import pickle
import numpy as np
import struct ## new
import zlib
import imutils
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QImage, QPixmap
import yolo_1 as yolo
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from imutils import perspective
from imutils.video import VideoStream

HOST='192.168.0.107'
PORT=8485

s=socket.socket(socket.AF_INET,socket.SOCK_STREAM)
print('Socket created')

s.bind((HOST,PORT))
print('Socket bind complete')
s.listen(10)
print('Socket now listening')

conn,addr=s.accept()


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(973, 580)
        font = QtGui.QFont()
        font.setPointSize(14)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 100, 941, 461))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lblName = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.lblName.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblName.setFont(font)
        self.lblName.setObjectName("lblName")
        self.horizontalLayout_4.addWidget(self.lblName)
        self.txtName = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txtName.setFont(font)
        self.txtName.setText("")
        self.txtName.setObjectName("txtName")
        self.horizontalLayout_4.addWidget(self.txtName)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lblGroup = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.lblGroup.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblGroup.setFont(font)
        self.lblGroup.setText("")
        self.lblGroup.setObjectName("lblGroup")
        self.horizontalLayout_5.addWidget(self.lblGroup)
        self.txtGroup = QtWidgets.QLabel(self.horizontalLayoutWidget)
        
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txtGroup.setFont(font)
        self.txtGroup.setObjectName("txtGroup")
        self.horizontalLayout_5.addWidget(self.txtGroup)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblClass = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.lblClass.setEnabled(True)
        self.lblClass.setMaximumSize(QtCore.QSize(100, 167))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblClass.setFont(font)
        self.lblClass.setObjectName("lblClass")
        self.horizontalLayout_2.addWidget(self.lblClass)
        self.txtClass = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.txtClass.setText("")
        self.txtClass.setObjectName("txtClass")
        self.horizontalLayout_2.addWidget(self.txtClass)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lblCode = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.lblCode.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblCode.setFont(font)
        self.lblCode.setObjectName("lblCode")
        self.horizontalLayout_3.addWidget(self.lblCode)
        self.txtCode = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.txtCode.setText("")
        self.txtCode.setObjectName("txtCode")
        self.horizontalLayout_3.addWidget(self.txtCode)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.photo = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.photo.setText("")
        self.photo.setObjectName("img")
        self.horizontalLayout.addWidget(self.photo)
        self.lblContent = QtWidgets.QLabel(self.centralwidget)
        self.lblContent.setGeometry(QtCore.QRect(270, 40, 431, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.lblContent.setFont(font)
        self.lblContent.setAlignment(QtCore.Qt.AlignCenter)
        self.lblContent.setObjectName("lblContent")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.Worker1 = Worker1()

        self.Worker1.start()
        self.Worker1.ImageUpdate.connect(self.ImageUpdateSlot)
        self.Worker1.showText.connect(self.textUpdate)

    def ImageUpdateSlot(self, Image):
        self.photo.setPixmap(QPixmap.fromImage(Image))
    def textUpdate(self, txt_code,txt_name,txt_group,txt_class):
        self.txtCode.setText(txt_code)
        self.txtName.setText(txt_name)
        self.txtGroup.setText(txt_group)
        self.txtClass.setText(txt_class)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblName.setText(_translate("MainWindow", "Họ và tên: "))
        self.lblGroup.setText(_translate("MainWindow", "Khóa: "))
        self.lblClass.setText(_translate("MainWindow", "Lớp:"))
        self.lblCode.setText(_translate("MainWindow", "Mã SV:"))
        self.lblContent.setText(_translate("MainWindow", "Ung dung hien thi thong tin"))
class Worker1(QThread):
    ImageUpdate = pyqtSignal(QImage)
    showText = pyqtSignal(str,str,str,str)
    def run(self):
        self.ThreadActive = True
        rect= QtCore.QRect(429, 115, 879-429,407-115 ) 
        
        data = b""
        payload_size = struct.calcsize(">L")
        print("payload_size: {}".format(payload_size))
        while self.ThreadActive:
                while len(data) < payload_size:
                    print("Recv: {}".format(len(data)))
                    data += conn.recv(4096)

                print("Done Recv: {}".format(len(data)))
                packed_msg_size = data[:payload_size]
                data = data[payload_size:]
                msg_size = struct.unpack(">L", packed_msg_size)[0]
                print("msg_size: {}".format(msg_size))
                while len(data) < msg_size:
                    data += conn.recv(4096)
                frame_data = data[:msg_size]
                data = data[msg_size:]

                frame=pickle.loads(frame_data, fix_imports=True, encoding="bytes")
                frame = cv2.imdecode(frame, cv2.IMREAD_COLOR)
                frame = imutils.resize(frame, width=1280, height=720)
                Image = cv2.cvtColor(frame, cv2.COLOR_RGB2BGR)
                ConvertToQtFormat = QImage(Image.data, Image.shape[1], Image.shape[0], QImage.Format_BGR888)

                Pic = ConvertToQtFormat.scaled(640, 480, Qt.KeepAspectRatio)
                Pic = ConvertToQtFormat.copy(rect)
                self.ImageUpdate.emit(Pic)

                try:
                    img=yolo.detec(frame)
                    text_card= yolo.getText(img,0.47,0.7,0.67,0.80)
                    text_name= yolo.getTextVie(img,0.47,0.82,0.35,0.46)
                    text_group= yolo.getText(img,0.47,0.82,0.46,0.57)
                    text_class= yolo.getText(img,0.47,0.82,0.58,0.66)
                    print(text_card)
                    conn.sendall(bytes(text_card,'UTF-8'))
                    self.showText.emit(text_card,text_name,text_group,text_class)
                except:

                    text_card= "No matching"
                    conn.sendall(b"No matching")
                    self.showText.emit("No matching","No matching","No matching","No matching")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
